name: Build Release Binaries

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # macOS
          - goos: darwin
            goarch: amd64
            suffix: darwin-amd64
          - goos: darwin
            goarch: arm64
            suffix: darwin-arm64

          # Windows
          - goos: windows
            goarch: amd64
            suffix: windows-amd64.exe
          - goos: windows
            goarch: arm64
            suffix: windows-arm64.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          check-latest: true

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 1
        run: |
          if [ "$GOOS" = "darwin" ]; then
            # For macOS cross-compilation, disable CGO for simplicity
            export CGO_ENABLED=0
          elif [ "$GOOS" = "windows" ]; then
            # Install mingw for Windows cross-compilation
            sudo apt-get update && sudo apt-get install -y gcc-mingw-w64
            if [ "$GOARCH" = "amd64" ]; then
              export CC=x86_64-w64-mingw32-gcc
            else
              export CC=aarch64-w64-mingw32-gcc
            fi
          fi

          # Build the binary
          go build -v -ldflags="-s -w -X main.version=${{ github.event.inputs.version }}" -o tracevibe-${{ matrix.suffix }}

      - name: Create tarball (Unix)
        if: matrix.goos != 'windows'
        run: |
          mkdir -p dist
          tar -czf dist/tracevibe-${{ matrix.suffix }}.tar.gz tracevibe-${{ matrix.suffix }}

      - name: Create zip (Windows)
        if: matrix.goos == 'windows'
        run: |
          mkdir -p dist
          zip dist/tracevibe-${{ matrix.suffix }}.zip tracevibe-${{ matrix.suffix }}

      - name: Generate checksums
        run: |
          cd dist
          if [ -f "tracevibe-${{ matrix.suffix }}.tar.gz" ]; then
            sha256sum tracevibe-${{ matrix.suffix }}.tar.gz > tracevibe-${{ matrix.suffix }}.tar.gz.sha256
          fi
          if [ -f "tracevibe-${{ matrix.suffix }}.zip" ]; then
            sha256sum tracevibe-${{ matrix.suffix }}.zip > tracevibe-${{ matrix.suffix }}.zip.sha256
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tracevibe-${{ matrix.suffix }}
          path: |
            dist/*
            tracevibe-${{ matrix.suffix }}
          retention-days: 30

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare release assets
        run: |
          mkdir -p release-assets
          find artifacts -name "*.tar.gz" -o -name "*.zip" -o -name "*.sha256" | while read file; do
            cp "$file" release-assets/
          done
          find artifacts -name "tracevibe-*" -type f ! -name "*.tar.gz" ! -name "*.zip" ! -name "*.sha256" | while read file; do
            cp "$file" release-assets/
          done
          ls -la release-assets/

      - name: Generate release notes
        id: release_notes
        run: |
          cat > release-notes.md << 'EOF'
          ## 🚀 TraceVibe ${{ github.event.inputs.version }}

          ### What's New
          - Requirements Traceability Matrix (RTM) management
          - SQLite-based storage with embedded web UI
          - LLM-assisted RTM generation with guidelines
          - Hierarchical requirements: Scope → User Stories → Tech Specs
          - Import/export functionality for JSON/YAML formats
          - Test coverage mapping and traceability

          ### Installation

          #### Quick Install (Recommended)
          ```bash
          # macOS/Windows
          curl -fsSL https://raw.githubusercontent.com/peshwar9/tracevibe/main/install.sh | bash

          # Or download binary directly for your platform below
          ```

          #### Manual Install
          1. Download the appropriate binary for your platform
          2. Make it executable: `chmod +x tracevibe-*` (macOS only)
          3. Move to PATH: `sudo mv tracevibe-* /usr/local/bin/tracevibe` (macOS) or add to Windows PATH

          ### Platform Support
          - ✅ macOS (Intel, Apple Silicon)
          - ✅ Windows (AMD64, ARM64)

          ### Usage
          ```bash
          # Generate RTM guidelines
          tracevibe guidelines -o rtm-guidelines.md

          # Import RTM data
          tracevibe import project-rtm.json --project myproject

          # Start web UI
          tracevibe serve
          ```

          ### Checksums
          All binaries include SHA256 checksums for verification.
          EOF

          echo "notes<<EOF" >> $GITHUB_OUTPUT
          cat release-notes.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: TraceVibe ${{ github.event.inputs.version }}
          body: ${{ steps.release_notes.outputs.notes }}
          draft: false
          prerelease: ${{ contains(github.event.inputs.version, '-') }}
          files: |
            release-assets/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update latest release info
        run: |
          echo "Release created successfully!"
          echo "Download URL: https://github.com/peshwar9/tracevibe/releases/tag/${{ github.event.inputs.version }}"